name: "ðŸ› Bug report"
description: Let us know about a bug!
labels: ['bug']
assignees:
  - BMTLab
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: >-
        Please provide a clear and concise description of what the bug is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it?
      description: >-
        Please be minimal and precise as possible.
        If your repo/run is public, please include a URL so it is easier for us to investigate.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: input
    id: version
    attributes:
      label: What version of the action are you using?
      placeholder: vX.Y.Z
      description: >-
        Please check the documentation first since different major versions can have different behaviors.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: >-
        How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false